AKIRA_DB_PATH = "/var/lib/akira-module/Database/ApplicationDB.db"

LOGIN_FIXED_URL = "http://localhost:9292/Login"
LOGIN_FIXED_USERNAME = "Sumato"
LOGIN_FIXED_PASSWORD = "Sumato.2272"

PLAYWRIGHT_SLOW_MO_MS = 150
PLAYWRIGHT_ACTION_WAIT_MS = 1500
PLAYWRIGHT_PRETYPE_WAIT_MS = 1500
PLAYWRIGHT_POSTTYPE_WAIT_MS = 1500
PLAYWRIGHT_POSTSUBMIT_WAIT_MS = 1500
PLAYWRIGHT_POSTCLOSE_WAIT_MS = 1500
PLAYWRIGHT_STORAGE_STATE_PATH = "/tmp/akira_playwright_state.json"
